/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 6:11:53 PM
 * Time to generate: 00:14.735 seconds
 *
 */

package org.mentawai.mail;

import com.agitar.lib.junit.AgitarTestCase;

public class EmailExceptionAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return EmailException.class;
    }
    
    public void testConstructor() throws Throwable {
        Throwable cause = new Throwable();
        EmailException emailException = new EmailException("testEmailExceptionMsg", cause);
        assertSame("emailException.getCause()", cause, emailException.getCause());
        assertEquals("emailException.getMessage()", "testEmailExceptionMsg", emailException.getMessage());
        // dependencies on static and environment state led to removal of 1 assertion
    }
    
    public void testConstructor1() throws Throwable {
        EmailException emailException = new EmailException("testEmailExceptionMsg");
        assertEquals("emailException.getMessage()", "testEmailExceptionMsg", emailException.getMessage());
    }
    
    public void testConstructor2() throws Throwable {
        new EmailException();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testConstructor3() throws Throwable {
        Throwable cause = new NoSuchFieldError();
        EmailException emailException = new EmailException(cause);
        assertSame("emailException.getCause()", cause, emailException.getCause());
        assertEquals("emailException.getMessage()", "java.lang.NoSuchFieldError", emailException.getMessage());
        // dependencies on static and environment state led to removal of 1 assertion
    }
    
    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new EmailException("testEmailExceptionMsg", null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(EmailException.class, ex);
        }
    }
    
    public void testConstructorThrowsNullPointerException1() throws Throwable {
        try {
            new EmailException((Throwable) null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(EmailException.class, ex);
        }
    }
}

