/**
 * Generated by Agitar build: JUnitFactory Version 2.1.0.000576 (Build date: Oct 19, 2007) [2.1.0.000576]
 * JDK Version: 1.5.0_11
 *
 * Generated on Nov 8, 2007 6:25:33 PM
 * Time to generate: 00:14.736 seconds
 *
 */

package org.mentawai.converter;

import com.agitar.lib.junit.AgitarTestCase;

public class ConversionExceptionAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return ConversionException.class;
    }
    
    public void testConstructor() throws Throwable {
        ConversionException conversionException = new ConversionException("testConversionExceptionMsg");
        assertEquals("conversionException.getMessage()", "testConversionExceptionMsg", conversionException.getMessage());
    }
    
    public void testConstructor1() throws Throwable {
        new ConversionException();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testConstructor2() throws Throwable {
        Exception e = new UnsupportedOperationException();
        ConversionException conversionException = new ConversionException(e);
        assertSame("conversionException.getCause()", e, conversionException.getCause());
        assertEquals("conversionException.getMessage()", "java.lang.UnsupportedOperationException", conversionException.getMessage());
        // dependencies on static and environment state led to removal of 1 assertion
    }
    
    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new ConversionException((Exception) null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(ConversionException.class, ex);
        }
    }
}

